---
abstract: 'music tension analysis'
author:
  - 'Jeremy Mates <jmates@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Music-Tension
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  Scalar::Util: 0
  Test::More: 0
resources:
  homepage: https://github.com/thrig/Music-Tension
  license: http://dev.perl.org/licenses/
  repository: https://github.com/thrig/Music-Tension
version: 0.50
